[2025-09-01T18:54:19.425+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-09-01T18:54:07.884437+00:00 [queued]>
[2025-09-01T18:54:19.531+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-09-01T18:54:07.884437+00:00 [queued]>
[2025-09-01T18:54:19.547+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-01T18:54:20.552+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-09-01 18:54:07.884437+00:00
[2025-09-01T18:54:20.686+0000] {standard_task_runner.py:57} INFO - Started process 243 to run task
[2025-09-01T18:54:20.793+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-09-01T18:54:07.884437+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpps8mz_q4']
[2025-09-01T18:54:20.828+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask python_job
[2025-09-01T18:54:21.178+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-09-01T18:54:07.884437+00:00 [running]> on host 7b2a3a75c36f
[2025-09-01T18:54:21.463+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T18:54:07.884437+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-01T18:54:07.884437+00:00'
[2025-09-01T18:54:21.515+0000] {spark_submit.py:273} INFO - Could not load connection string spark-conn, defaulting to yarn
[2025-09-01T18:54:21.527+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py
[2025-09-01T18:54:28.248+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-09-01T18:54:45.791+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-09-01T18:54:45.895+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-09-01T18:54:45.896+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-09-01T18:54:45.903+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-09-01T18:54:45.903+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-09-01T18:54:45.905+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-09-01T18:54:45.906+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-09-01T18:54:45.907+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-09-01T18:54:45.907+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-09-01T18:54:45.911+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-09-01T18:54:45.912+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-09-01T18:54:46.193+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2025-09-01T18:54:46.275+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250901T185407, start_date=20250901T185419, end_date=20250901T185446
[2025-09-01T18:54:46.858+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task python_job (Cannot execute: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 243)
[2025-09-01T18:54:46.957+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-01T18:54:47.240+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
