[2025-08-18T15:42:46.679+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:42:43.525669+00:00 [queued]>
[2025-08-18T15:42:46.695+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-18T15:42:43.525669+00:00 [queued]>
[2025-08-18T15:42:46.696+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-18T15:42:46.715+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-18 15:42:43.525669+00:00
[2025-08-18T15:42:46.724+0000] {standard_task_runner.py:57} INFO - Started process 8536 to run task
[2025-08-18T15:42:46.726+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-08-18T15:42:43.525669+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpnw33c2co']
[2025-08-18T15:42:46.730+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask python_job
[2025-08-18T15:42:46.820+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-08-18T15:42:43.525669+00:00 [running]> on host 81b7fe425a18
[2025-08-18T15:42:46.903+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T15:42:43.525669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T15:42:43.525669+00:00'
[2025-08-18T15:42:46.915+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-18T15:42:46.917+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-18T15:42:47.341+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-18T15:42:48.575+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-18T15:42:50.466+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-18T15:42:50.470+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkContext: Running Spark version 4.0.0
[2025-08-18T15:42:50.472+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-18T15:42:50.472+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkContext: Java version 17.0.15
[2025-08-18T15:42:50.495+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceUtils: ==============================================================
[2025-08-18T15:42:50.496+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-18T15:42:50.496+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceUtils: ==============================================================
[2025-08-18T15:42:50.499+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-18T15:42:50.522+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-18T15:42:50.524+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceProfile: Limiting resource is cpu
[2025-08-18T15:42:50.525+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-18T15:42:50.570+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:42:50.571+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:42:50.572+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:42:50.572+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:42:50.574+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:42:50.780+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO Utils: Successfully started service 'sparkDriver' on port 35813.
[2025-08-18T15:42:50.812+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkEnv: Registering MapOutputTracker
[2025-08-18T15:42:50.827+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-18T15:42:50.846+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-18T15:42:50.847+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-18T15:42:50.851+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-18T15:42:50.873+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-2b9e5e6b-bba9-4b1b-8875-f72c19ea1443
[2025-08-18T15:42:50.893+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:50 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-18T15:42:51.020+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-18T15:42:51.083+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-18T15:42:51.120+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SparkContext: Added JAR file:///opt/spark/external-jars/apache-spark-sql-connector.jar at spark://81b7fe425a18:35813/jars/apache-spark-sql-connector.jar with timestamp 1755531770459
[2025-08-18T15:42:51.138+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SecurityManager: Changing view acls to: ***
[2025-08-18T15:42:51.139+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SecurityManager: Changing modify acls to: ***
[2025-08-18T15:42:51.139+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-18T15:42:51.139+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-18T15:42:51.140+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-18T15:42:51.252+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-08-18T15:42:51.292+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO TransportClientFactory: Successfully created connection to spark-master/172.18.0.3:7077 after 22 ms (0 ms spent in bootstraps)
[2025-08-18T15:42:51.369+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250818154251-0008
[2025-08-18T15:42:51.372+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250818154251-0008/0 on worker-20250818041359-172.18.0.5-40851 (172.18.0.5:40851) with 2 core(s)
[2025-08-18T15:42:51.379+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneSchedulerBackend: Granted executor ID app-20250818154251-0008/0 on hostPort 172.18.0.5:40851 with 2 core(s), 1024.0 MiB RAM
[2025-08-18T15:42:51.380+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42131.
[2025-08-18T15:42:51.381+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO NettyBlockTransferService: Server created on 81b7fe425a18:42131
[2025-08-18T15:42:51.384+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-18T15:42:51.402+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 81b7fe425a18, 42131, None)
[2025-08-18T15:42:51.407+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO BlockManagerMasterEndpoint: Registering block manager 81b7fe425a18:42131 with 434.4 MiB RAM, BlockManagerId(driver, 81b7fe425a18, 42131, None)
[2025-08-18T15:42:51.410+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 81b7fe425a18, 42131, None)
[2025-08-18T15:42:51.411+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 81b7fe425a18, 42131, None)
[2025-08-18T15:42:51.495+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250818154251-0008/0 is now RUNNING
[2025-08-18T15:42:51.578+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:51 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-18T15:42:54.630+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:54 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.5:47378) with ID 0, ResourceProfileId 0
[2025-08-18T15:42:54.731+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:42:54.733+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-08-18T15:42:54.733+0000] {spark_submit.py:579} INFO - conn = connection.create_connection(
[2025-08-18T15:42:54.734+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
[2025-08-18T15:42:54.734+0000] {spark_submit.py:579} INFO - for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
[2025-08-18T15:42:54.735+0000] {spark_submit.py:579} INFO - File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
[2025-08-18T15:42:54.735+0000] {spark_submit.py:579} INFO - for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
[2025-08-18T15:42:54.736+0000] {spark_submit.py:579} INFO - socket.gaierror: [Errno -2] Name or service not known
[2025-08-18T15:42:54.737+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.738+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:42:54.743+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.746+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:42:54.747+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2025-08-18T15:42:54.747+0000] {spark_submit.py:579} INFO - httplib_response = self._make_request(
[2025-08-18T15:42:54.748+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2025-08-18T15:42:54.749+0000] {spark_submit.py:579} INFO - self._validate_conn(conn)
[2025-08-18T15:42:54.749+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2025-08-18T15:42:54.750+0000] {spark_submit.py:579} INFO - conn.connect()
[2025-08-18T15:42:54.751+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
[2025-08-18T15:42:54.751+0000] {spark_submit.py:579} INFO - self.sock = conn = self._new_conn()
[2025-08-18T15:42:54.751+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-08-18T15:42:54.752+0000] {spark_submit.py:579} INFO - raise NewConnectionError(
[2025-08-18T15:42:54.752+0000] {spark_submit.py:579} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x730d17f46050>: Failed to establish a new connection: [Errno -2] Name or service not known
[2025-08-18T15:42:54.753+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.753+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:42:54.754+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.754+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:42:54.754+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
[2025-08-18T15:42:54.755+0000] {spark_submit.py:579} INFO - resp = conn.urlopen(
[2025-08-18T15:42:54.755+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2025-08-18T15:42:54.756+0000] {spark_submit.py:579} INFO - retries = retries.increment(
[2025-08-18T15:42:54.756+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-08-18T15:42:54.757+0000] {spark_submit.py:579} INFO - raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-08-18T15:42:54.757+0000] {spark_submit.py:579} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x730d17f46050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:42:54.760+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.760+0000] {spark_submit.py:579} INFO - During handling of the above exception, another exception occurred:
[2025-08-18T15:42:54.761+0000] {spark_submit.py:579} INFO - 
[2025-08-18T15:42:54.763+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-18T15:42:54.763+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 32, in <module>
[2025-08-18T15:42:54.765+0000] {spark_submit.py:579} INFO - response = requests.get(url, headers=headers)
[2025-08-18T15:42:54.766+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
[2025-08-18T15:42:54.767+0000] {spark_submit.py:579} INFO - return request("get", url, params=params, **kwargs)
[2025-08-18T15:42:54.767+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
[2025-08-18T15:42:54.768+0000] {spark_submit.py:579} INFO - return session.request(method=method, url=url, **kwargs)
[2025-08-18T15:42:54.768+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
[2025-08-18T15:42:54.769+0000] {spark_submit.py:579} INFO - resp = self.send(prep, **send_kwargs)
[2025-08-18T15:42:54.769+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
[2025-08-18T15:42:54.769+0000] {spark_submit.py:579} INFO - r = adapter.send(request, **kwargs)
[2025-08-18T15:42:54.770+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
[2025-08-18T15:42:54.770+0000] {spark_submit.py:579} INFO - raise ConnectionError(e, request=request)
[2025-08-18T15:42:54.771+0000] {spark_submit.py:579} INFO - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.chess.com', port=443): Max retries exceeded with url: /pub/leaderboards (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x730d17f46050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
[2025-08-18T15:42:55.076+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.5:32945 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.5, 32945, None)
[2025-08-18T15:42:55.163+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-18T15:42:55.167+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-18T15:42:55.192+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO SparkUI: Stopped Spark web UI at http://81b7fe425a18:4040
[2025-08-18T15:42:55.197+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-18T15:42:55.197+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-18T15:42:55.231+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-18T15:42:55.284+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-18T15:42:55.288+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO MemoryStore: MemoryStore cleared
[2025-08-18T15:42:55.292+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO BlockManager: BlockManager stopped
[2025-08-18T15:42:55.322+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-18T15:42:55.328+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-18T15:42:55.374+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO SparkContext: Successfully stopped SparkContext
[2025-08-18T15:42:55.377+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO ShutdownHookManager: Shutdown hook called
[2025-08-18T15:42:55.379+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-b601f1d7-2477-4747-ad4d-afd8261e6bd1
[2025-08-18T15:42:55.425+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-b601f1d7-2477-4747-ad4d-afd8261e6bd1/pyspark-f2ec5d82-1cb1-4b69-b882-f5a0e43eff66
[2025-08-18T15:42:55.497+0000] {spark_submit.py:579} INFO - 25/08/18 15:42:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-ba101462-3235-4e5a-9def-d964e3cf72cb
[2025-08-18T15:42:55.645+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-18T15:42:55.657+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250818T154243, start_date=20250818T154246, end_date=20250818T154255
[2025-08-18T15:42:55.713+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task python_job (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 8536)
[2025-08-18T15:42:55.750+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-18T15:42:55.788+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
