[2025-09-01T18:54:21.960+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-09-01T18:54:22.170+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job scheduled__2025-09-01T00:00:00+00:00 [queued]>
[2025-09-01T18:54:22.174+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-01T18:54:22.265+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-09-01 00:00:00+00:00
[2025-09-01T18:54:22.329+0000] {standard_task_runner.py:57} INFO - Started process 271 to run task
[2025-09-01T18:54:22.375+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'scheduled__2025-09-01T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpb2zql2xe']
[2025-09-01T18:54:22.394+0000] {standard_task_runner.py:85} INFO - Job 25: Subtask python_job
[2025-09-01T18:54:22.735+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job scheduled__2025-09-01T00:00:00+00:00 [running]> on host 7b2a3a75c36f
[2025-09-01T18:54:23.047+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Kudzaishe Manyanya' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-01T00:00:00+00:00'
[2025-09-01T18:54:23.074+0000] {spark_submit.py:273} INFO - Could not load connection string spark-conn, defaulting to yarn
[2025-09-01T18:54:23.076+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py
[2025-09-01T18:54:27.934+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-09-01T18:54:45.241+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-09-01T18:54:45.294+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-09-01T18:54:45.296+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-09-01T18:54:45.298+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-09-01T18:54:45.299+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-09-01T18:54:45.300+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-09-01T18:54:45.302+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-09-01T18:54:45.302+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-09-01T18:54:45.304+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-09-01T18:54:45.304+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-09-01T18:54:45.304+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-09-01T18:54:46.250+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2025-09-01T18:54:46.326+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250901T000000, start_date=20250901T185421, end_date=20250901T185446
[2025-09-01T18:54:46.838+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 25 for task python_job (Cannot execute: spark-submit --master yarn --jars /opt/spark/external-jars/apache-spark-sql-connector.jar --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 271)
[2025-09-01T18:54:46.922+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-01T18:54:47.136+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
